### ISSUE TITLE
Bug in gradle dependencies in README.md

### ISSUE THREAD

**Issue by henrichg** [thelittlefireman/AppKillerManager#1]
Fix it to com.thelittlefireman:AppKillerManager:2.0.0.

**Comment by thelittlefireman** [comment]
Oh thanks you ! it's ok now ;)

**Comment by henrichg** [comment]
I have in project gradle in buildscript and allprojects this:

    repositories {
        google()
        maven { url "https://maven.google.com" }
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }

and working.

**Comment by thelittlefireman** [comment]
i fixed a typo i think it's working now with jcenter :)

**Comment by moxgeek** [comment]
the same issues in 2.1.1 : 

> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.thelittlefireman:AppKillerManager:2.1.1.
