### ISSUE TITLE
Huawei PLK-L01, KillerManager.doActionAutoStart() not opens activity

### ISSUE THREAD

**Issue by henrichg** [thelittlefireman/AppKillerManager#2]
DeviceBase.getExtraDebugInformations():
ROM_VERSION=EmotionUI_4.0
HuaweiSystemManagerVersionMethod:5
HuaweiSystemManagerPackageVersion:4.0.1.300
huawei.intent.action.HSM_BOOTAPP_MANAGER=true
huawei.intent.action.HSM_PROTECTED_APPS=true
huawei.intent.action.NOTIFICATIONMANAGER=true
com.huawei.systemmanager com.huawei.systemmanager.optimize.bootstart.BootStartActivity=false
com.huawei.systemmanager com.huawei.systemmanager.startupmgr.ui.StartupNormalAppListActivity=true
com.huawei.systemmanager com.huawei.permissionmanager.ui.MainActivity=true
0

DeviceBase.getActionAutoStart():
Intent { act=huawei.intent.action.HSM_BOOTAPP_MANAGER cat=[android.intent.category.DEFAULT] flg=0x10000000 }

**Comment by thelittlefireman** [comment]
Thanks for report i will look into that

**Comment by thelittlefireman** [comment]
I can confirm that there is no handle action on huawei for AutoStart (look at the readMe) Only the "protected app" activity is used. However the action "huawei.intent.action.HSM_BOOTAPP_MANAGER" is implemented in the com.huawei.systemmanager but doesn't start any activity. Maybe reverse the apk will help to understood but i have no time for now.

Then i don't think there is a AutoStart killer in huawei ?

**Comment by henrichg** [comment]
I do not found any setting for this in my Honor 7.
Better will be to not return intent from DeviceBase.getActionAutoStart().

**Comment by henrichg** [comment]
Tested, working good.

**Comment by fukemy** [comment]
not working for mi 8 pro, someone faced it?
