### ISSUE TITLE
Galaxy Nexus: KillerManager.doActionPowerSaving() do not opens activity

### ISSUE THREAD

**Issue by henrichg** [thelittlefireman/AppKillerManager#3]
KillerManager.isActionAvailable(getActivity(), KillerManager.Actions.ACTION_POWERSAVING) returns true but KillerManager.doActionPowerSaving() do not opens activity. 
By me bug is in KillerManager.isActionAvailable(getActivity(), KillerManager.Actions.ACTION_POWERSAVING).
Galaxy Nexus, Android 4.4.4.

**Comment by thelittlefireman** [comment]
Thanks for the reports, did you get some logs ? Intent is null ?

Does it open the dialog but do nothins on clic "open settings" ?

**Comment by thelittlefireman** [comment]
I don't find any power saving or app killer on my s4 mini 4.4.4. I will just add an exclusion for those phones. If you find something intresting feel free to reopen the issue.

thanks again for your contribution :)

**Comment by henrichg** [comment]
My code snipest:
`        preference = prefMng.findPreference(PREF_APPLICATION_POWER_MANAGER);
        if (preference != null) {
            if (KillerManager.isActionAvailable(getActivity(), KillerManager.Actions.ACTION_POWERSAVING)) {
                preference.setOnPreferenceClickListener(new Preference.OnPreferenceClickListener() {
                    @Override
                    public boolean onPreferenceClick(Preference preference) {
                        try {
                            KillerManager.doActionPowerSaving(getActivity());
                        }catch (Exception e) {
                            AlertDialog.Builder dialogBuilder = new AlertDialog.Builder(getActivity());
                            dialogBuilder.setMessage(R.string.setting_screen_not_found_alert);
                            dialogBuilder.setPositiveButton(android.R.string.ok, null);
                            AlertDialog dialog = dialogBuilder.create();
                            dialog.show();
                        }
                        return false;
                    }
                });
            } else {
                PreferenceScreen preferenceCategory = (PreferenceScreen) findPreference("categorySystem");
                preferenceCategory.removePreference(preference);
            }
`
Preference is displayed because KillerManager.isActionAvailable(getActivity(), KillerManager.Actions.ACTION_POWERSAVING) returns true. Bud call of KillerManager.doActionPowerSaving(getActivity()); do not open anything.

logs:
manufacturer=SAMSUNG
device.getExtraDebugInformations()=null
device.getActionPowerSaving=null
But KillerManager.isActionAvailable() returns true. Why?

**Comment by thelittlefireman** [comment]
I've just updat the library could you please test if it's solved ?

**Comment by henrichg** [comment]
Tested with Galaxy Nexus -  KillerManager.isActionAvailable() returns false = OK.
Tested with Galaxy S8 -  -  KillerManager.isActionAvailable() returns true, KillerManager.doActionPowerSaving() opens good activity = OK.
